[build]
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  # Disable secrets scanning for build output since VITE_ variables are intentionally exposed to client-side
  SECRETS_SCAN_ENABLED = "false"

[dev]
  targetPort = 8084

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 

# Auto-Resolution Function (Currently Paused)
# Uncomment the schedule below when you want to enable auto-resolution
[functions."auto-resolve-user-dependency"]
  # schedule = "0 2 * * *"  # Daily at 2 AM UTC - PAUSED
  # To enable: uncomment the line above