// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mvwxlfvvxwhzobyjpxsg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im12d3hsZnZ2eHdoem9ieWpweHNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NDc4MzQsImV4cCI6MjA2NjQyMzgzNH0.ev1ppO6gsRBMb0rVbmewiTAy9vHrS5SIxuP0l4IpSr0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);